// Set current order dates here when ready. Blank dates hide the date line.
const ORDER_START = "";
const ORDER_END = "";
const CATEGORY_ORDER = ["All Products", "Packs", "Jerseys & Pants", "Pants & Shorts", "Shirts & Tops", "Hoodies & Jackets", "Women's Wear", "Youth Wear", "Misc"];
function normalizeCategory(value){
 const label=String(value).trim();
 const key=label.toLowerCase().replace(/[’']/g,"'");
 const aliases={"pack":"Packs","packs":"Packs","jerseys":"Jerseys & Pants","jersey & pants":"Jerseys & Pants","jerseys & pants":"Jerseys & Pants","pants & jerseys":"Jerseys & Pants","women's apparel":"Women's Wear","womens apparel":"Women's Wear","women's wear":"Women's Wear","womens wear":"Women's Wear","youth apparel":"Youth Wear","youth wear":"Youth Wear","head gear":"Misc","headwear":"Misc","bags & accessories":"Misc","team items":"Misc","game gear":"Misc"};
 return aliases[key] || CATEGORY_ORDER.find(c=>c.toLowerCase()===key) || label;
}
function catalogLink(category){return category && category!=="All Products" ? "products.html?group="+encodeURIComponent(category):"products.html";}
function installSiteNavigation(){
 const header=document.createElement("header");header.className="site-header";
 header.innerHTML='<button class="site-menu-button" aria-label="Open menu" aria-expanded="false" aria-controls="sideMenu">☰</button><a class="site-brand" href="index.html">FOX SQUAD SWAG</a><a class="site-cart" href="cart.html" aria-label="View cart">🛒<span id="cartCount" class="cart-count"></span></a>';
 document.body.prepend(header);
 const overlay=document.createElement("div");overlay.className="site-overlay";overlay.hidden=true;
 const menu=document.createElement("nav");menu.id="sideMenu";menu.className="site-menu";menu.hidden=true;menu.setAttribute("aria-label","Main navigation");
 menu.innerHTML='<button class="menu-close" aria-label="Close menu">×</button><a href="index.html">Home</a><button class="catalog-toggle" aria-expanded="false" aria-controls="catalogDropdown">Catalog <span>▼</span></button><div id="catalogDropdown" hidden>'+CATEGORY_ORDER.map(c=>'<a class="category-link" href="'+escapeHTML(catalogLink(c))+'">'+escapeHTML(c)+'</a>').join('')+'</div><a href="cart.html">Cart</a>';
 document.body.append(overlay,menu);
 const footer=document.createElement("footer");footer.className="site-footer";footer.innerHTML='<a href="index.html">Home</a><a href="products.html">Catalog</a><a href="cart.html">Cart</a>';document.body.append(footer);
 const opener=header.querySelector('button');let previousOverflow='';
 function setMenu(open){menu.hidden=!open;overlay.hidden=!open;opener.setAttribute('aria-expanded',String(open));if(open){previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';menu.querySelector('button').focus();}else{document.body.style.overflow=previousOverflow;opener.focus();}}
 opener.onclick=()=>setMenu(true);overlay.onclick=()=>setMenu(false);menu.querySelector('.menu-close').onclick=()=>setMenu(false);
 menu.querySelector('.catalog-toggle').onclick=function(){const dropdown=menu.querySelector('#catalogDropdown');dropdown.hidden=!dropdown.hidden;this.setAttribute('aria-expanded',String(!dropdown.hidden));this.querySelector('span').textContent=dropdown.hidden?'▼':'▲';};
 document.addEventListener('keydown',e=>{if(menu.hidden)return;if(e.key==='Escape'){setMenu(false);return;}if(e.key==='Tab'){const focusable=[...menu.querySelectorAll('a,button')].filter(x=>x.getClientRects().length);const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 updateCartCount();
}
function siteCard(product){const href='product.html?id='+encodeURIComponent(makeProductId(product.name));const price=product.pricePending||product.price==null?'Price pending':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(product.price);return `<article class="site-card"><a href="${escapeHTML(href)}"><img src="${escapeHTML(productImage(product))}" alt="${escapeHTML(product.name)}" loading="lazy" onerror="this.onerror=null;this.src=NO_IMAGE"></a><h3>${escapeHTML(product.name)}</h3><p>${escapeHTML(price)}</p><a class="site-button" href="${escapeHTML(href)}">Add to Order</a></article>`;}
async function siteProducts(){const [products,imageRows]=await Promise.all([loadProducts(),loadImageRows()]);return products.map(p=>{applyImagesToProduct(p,imageRows);return {...p,categories:[...new Set((p.categories||[]).flatMap(c=>c.toLowerCase()==='tracksuits'?['Hoodies & Jackets','Pants & Shorts']:[normalizeCategory(c)]))]};});}
function categoryProducts(products,category){return category==='All Products'?products:products.filter(p=>p.categories.includes(category));}
function makeProductRow(title,products,id){if(!products.length)return '';return `<section class="site-section"><div class="row-heading"><h2>${escapeHTML(title)}</h2><div class="row-controls"><button data-row="${id}" data-direction="-1" aria-label="Previous ${escapeHTML(title)}">‹</button><button data-row="${id}" data-direction="1" aria-label="Next ${escapeHTML(title)}">›</button></div></div><div class="product-row" id="${id}">${products.map(siteCard).join('')}</div></section>`;}
async function renderHomepage(){const message=document.getElementById('catalogMessage');try{const products=await siteProducts();document.getElementById('homeRows').innerHTML=makeProductRow('Featured',products.filter(p=>p.featured),'featuredRow')+CATEGORY_ORDER.slice(1).map((c,i)=>makeProductRow(c,categoryProducts(products,c),'categoryRow'+i)).join('');document.querySelectorAll('[data-row]').forEach(button=>button.onclick=()=>{const row=document.getElementById(button.dataset.row);const card=row.querySelector('.site-card');row.scrollBy({left:(card.getBoundingClientRect().width+18)*Number(button.dataset.direction),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});message.hidden=products.length>0;message.textContent='No available products.';if(ORDER_START&&ORDER_END){const dates=document.getElementById('orderDates');dates.textContent=ORDER_START+' – '+ORDER_END;dates.hidden=false;}}catch(e){console.error(e);message.textContent='The catalog could not load. Please refresh or try again later.';}}
async function renderCatalog(){const message=document.getElementById('catalogMessage');try{const products=await siteProducts();const raw=new URLSearchParams(location.search).get('group')||'All Products';const selected=normalizeCategory(raw);document.getElementById('categoryFilters').innerHTML=CATEGORY_ORDER.map(c=>'<a href="'+escapeHTML(catalogLink(c))+'" '+(c===selected?'aria-current="page"':'')+'>'+escapeHTML(c)+'</a>').join('');document.getElementById('catalogHeading').textContent=selected;const shown=categoryProducts(products,selected);document.getElementById('productGrid').innerHTML=shown.map(siteCard).join('');message.hidden=shown.length>0;message.textContent='No available products in this category.';}catch(e){console.error(e);message.textContent='The catalog could not load. Please refresh or try again later.';}}
installSiteNavigation();
